
vars:
  - &NegDirCSVFile              TiltLargeStepNegDir_[COUNTER]
  - &PosDirCSVFile              TiltLargeStepPosDir_[COUNTER]

  # Process functions

  # Functions to be applied to &NegDirCSVFile
  - &LabelForNegDirCSVFile TiltLargeStepNegDir

  - &GetMaxVelocityInstforNegDir
    Name: GetMaxVelocityInst
    Args: 'timeWindow_ms: 300'
    Label: *LabelForNegDirCSVFile
  
  - &GetStartOfMotionCommandNegDir
    Name: GetStartOfMotionCommand
    Args: 'VThresh: -0.002, SystemDelay_ms: 50'
    Label: *LabelForNegDirCSVFile  



  # Functions to be applied to &PosDirCSVFile
  - &LabelForPosDirCSVFile   TiltLargeStepPosDir
  
  - &GetMaxVelocityInstforPosDir
    Name: GetMaxVelocityInst
    Args: 'timeWindow_ms: 300'
    Label: *LabelForPosDirCSVFile
  
  - &GetStartOfMotionCommandPosDir
    Name: GetStartOfMotionCommand
    Args: 'VThresh: 0.002, SystemDelay_ms: 50'
    Label: *LabelForPosDirCSVFile


PostOperations:

  - Type: MultiProcessLogFiles
    LogName: *NegDirCSVFile
    ProcessFunctions:
      - <<: *GetMaxVelocityInstforNegDir
      - <<: *GetStartOfMotionCommandNegDir

  - Type: MultiProcessLogFiles
    LogName: *PosDirCSVFile
    ProcessFunctions:
      - <<: *GetMaxVelocityInstforPosDir
      - <<: *GetStartOfMotionCommandPosDir
