
vars:
  - &NegDirCSVFile              ReachLargeStepNegDir_[COUNTER]
  - &PosDirCSVFile              ReachLargeStepPosDir_[COUNTER]

  # Process functions

  # Functions to be applied to &NegDirCSVFile
  - &LabelForNegDirCSVFile ReachLargeStepNegDir
  
  
  - &GetMaxVelocityInstforNegDir
    Name: GetMaxVelocityInst
    Args: 'timeWindow_ms: 300'
    Label: *LabelForNegDirCSVFile
  
  - &GetStartOfMotionCommandNegDir
    Name: GetStartOfMotionCommand
    Args: 'VThresh: -5.0, SystemDelay_ms: 50'
    Label: *LabelForNegDirCSVFile  

  # - &GetMaxVelocityErrorforNegDir
  #   Name: GetMaxVelocityError
  #   Args: 'timeWindow_ms: 500.0'
  #   Label: *LabelForNegDirCSVFile


  # Functions to be applied to &PosDirCSVFile
  - &LabelForPosDirCSVFile   ReachLargeStepPosDir
  
  - &GetMaxVelocityInstforPosDir
    Name: GetMaxVelocityInst
    Args: 'timeWindow_ms: 300'
    Label: *LabelForPosDirCSVFile
  
  # - &GetMaxVelocityErrorforPosDir
  #   Name: GetMaxVelocityError
  #   Args: 'timeWindow_ms: 500.0'
  #   Label: *LabelForPosDirCSVFile

  - &GetStartOfMotionCommandPosDir
    Name: GetStartOfMotionCommand
    Args: 'VThresh: 5.0, SystemDelay_ms: 50'
    Label: *LabelForPosDirCSVFile


PostOperations:

  - Type: MultiProcessLogFiles
    LogName: *NegDirCSVFile
    ProcessFunctions:
      - <<: *GetMaxVelocityInstforNegDir
      - <<: *GetStartOfMotionCommandNegDir

  - Type: MultiProcessLogFiles
    LogName: *PosDirCSVFile
    ProcessFunctions:
      - <<: *GetMaxVelocityInstforPosDir
      - <<: *GetStartOfMotionCommandPosDir
